{
    "output": "",
    "errors": ".FF.F\n======================================================================\nFAIL: test_custom_2 (__main__.TestClimbStairs.test_custom_2)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\70_climbing-stairs\\test.py\", line 37, in test_custom_2\n    self.assertEqual(sol.climbStairs(4), 5)\nAssertionError: 3 != 5\n\n======================================================================\nFAIL: test_custom_3 (__main__.TestClimbStairs.test_custom_3)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\70_climbing-stairs\\test.py\", line 45, in test_custom_3\n    self.assertEqual(sol.climbStairs(5), 8)\nAssertionError: 5 != 8\n\n======================================================================\nFAIL: test_example_2 (__main__.TestClimbStairs.test_example_2)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\70_climbing-stairs\\test.py\", line 21, in test_example_2\n    self.assertEqual(sol.climbStairs(3), 3)\nAssertionError: 2 != 3\n\n----------------------------------------------------------------------\nRan 5 tests in 0.002s\n\nFAILED (failures=3)\n",
    "returncode": 1
}