{
    "output": "",
    "errors": "FFF\n======================================================================\nFAIL: test_edge_cases (__main__.TestMaxFrequencyElements.test_edge_cases)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-New\\LeetCodeTasks - Testing\\Tests\\3005_count-elements-with-maximum-frequency\\test.py\", line 33, in test_edge_cases\n    self.assertEqual(self.solution.maxFrequencyElements([7,7,7,7]), 4)\nAssertionError: 0 != 4\n\n======================================================================\nFAIL: test_examples (__main__.TestMaxFrequencyElements.test_examples)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-New\\LeetCodeTasks - Testing\\Tests\\3005_count-elements-with-maximum-frequency\\test.py\", line 25, in test_examples\n    self.assertEqual(self.solution.maxFrequencyElements([1,2,3,4,5]), 5)\nAssertionError: 0 != 5\n\n======================================================================\nFAIL: test_large_input (__main__.TestMaxFrequencyElements.test_large_input)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-New\\LeetCodeTasks - Testing\\Tests\\3005_count-elements-with-maximum-frequency\\test.py\", line 49, in test_large_input\n    self.assertEqual(self.solution.maxFrequencyElements(nums), 40)\nAssertionError: 62 != 40\n\n----------------------------------------------------------------------\nRan 3 tests in 0.002s\n\nFAILED (failures=3)\n",
    "returncode": 1
}