{
    "output": "",
    "errors": "FFFFFFF\n======================================================================\nFAIL: test_example_1 (__main__.TestSolution.test_example_1)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-New\\LeetCodeTasks - Testing\\Tests\\3000_maximum-area-of-longest-diagonal-rectangle\\test.py\", line 17, in test_example_1\n    self.assertEqual(self.solution.areaOfMaxDiagonal([[9, 3], [8, 6]]), 48)\nAssertionError: 0 != 48\n\n======================================================================\nFAIL: test_example_2 (__main__.TestSolution.test_example_2)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-New\\LeetCodeTasks - Testing\\Tests\\3000_maximum-area-of-longest-diagonal-rectangle\\test.py\", line 23, in test_example_2\n    self.assertEqual(self.solution.areaOfMaxDiagonal([[3, 4], [4, 3]]), 12)\nAssertionError: 0 != 12\n\n======================================================================\nFAIL: test_maximum_boundaries (__main__.TestSolution.test_maximum_boundaries)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-New\\LeetCodeTasks - Testing\\Tests\\3000_maximum-area-of-longest-diagonal-rectangle\\test.py\", line 47, in test_maximum_boundaries\n    self.assertEqual(self.solution.areaOfMaxDiagonal([[100, 100]] * 100), 10000)\nAssertionError: 0 != 10000\n\n======================================================================\nFAIL: test_minimum_boundaries (__main__.TestSolution.test_minimum_boundaries)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-New\\LeetCodeTasks - Testing\\Tests\\3000_maximum-area-of-longest-diagonal-rectangle\\test.py\", line 53, in test_minimum_boundaries\n    self.assertEqual(self.solution.areaOfMaxDiagonal([[1, 1]] * 100), 1)\nAssertionError: 0 != 1\n\n======================================================================\nFAIL: test_same_area_different_diagonal (__main__.TestSolution.test_same_area_different_diagonal)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-New\\LeetCodeTasks - Testing\\Tests\\3000_maximum-area-of-longest-diagonal-rectangle\\test.py\", line 41, in test_same_area_different_diagonal\n    self.assertEqual(self.solution.areaOfMaxDiagonal([[6, 7], [7, 6]]), 42)\nAssertionError: 0 != 42\n\n======================================================================\nFAIL: test_same_diagonal_different_area (__main__.TestSolution.test_same_diagonal_different_area)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-New\\LeetCodeTasks - Testing\\Tests\\3000_maximum-area-of-longest-diagonal-rectangle\\test.py\", line 35, in test_same_diagonal_different_area\n    self.assertEqual(self.solution.areaOfMaxDiagonal([[10, 10], [14, 2]]), 100)\nAssertionError: 0 != 100\n\n======================================================================\nFAIL: test_single_rectangle (__main__.TestSolution.test_single_rectangle)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-New\\LeetCodeTasks - Testing\\Tests\\3000_maximum-area-of-longest-diagonal-rectangle\\test.py\", line 29, in test_single_rectangle\n    self.assertEqual(self.solution.areaOfMaxDiagonal([[5, 5]]), 25)\nAssertionError: 0 != 25\n\n----------------------------------------------------------------------\nRan 7 tests in 0.003s\n\nFAILED (failures=7)\n",
    "returncode": 1
}